module.exports = [
  {
    id: 1,
    stock: 4,
    gender: "women",
    productType: "shirt",
    productImg: "http://localhost:5000/women-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 2,
    stock: 4,
    gender: "women",
    productType: "shirt",
    productImg: "http://localhost:5000/women-2.jpg",
    productName: "Pure Pineapple,",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 3,
    stock: 4,
    gender: "women",
    productType: "shirt",
    productImg: "http://localhost:5000/women-3.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 4,
    stock: 4,
    gender: "women",
    productType: "bag",
    productImg: "http://localhost:5000/women-4.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 5,
    stock: 5,
    gender: "women",
    productType: "bag",
    productImg: "http://localhost:5000/women-2.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 6,
    stock: 3,
    gender: "women",
    productType: "bag",
    productImg: "http://localhost:5000/women-2.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 7,
    stock: 4,
    gender: "women",
    productType: "bag",
    productImg: "http://localhost:5000/women-2.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 8,
    stock: 4,
    gender: "women",
    productType: "bag",
    productImg: "http://localhost:5000/women-2.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 9,
    stock: 7,
    gender: "women",
    productType: "bag",
    productImg: "http://localhost:5000/women-2.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 10,
    stock: 4,
    gender: "women",
    productType: "bag",
    productImg: "http://localhost:5000/women-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 11,
    stock: 4,
    gender: "women",
    productType: "bag",
    productImg: "http://localhost:5000/women-2.jpg",
    productName: "Pure Pineapple,",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 12,
    stock: 4,
    gender: "women",
    productType: "bag",
    productImg: "http://localhost:5000/women-3.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 13,
    stock: 4,
    gender: "women",
    productType: "bag",
    productImg: "http://localhost:5000/women-3.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },

  {
    id: 14,
    stock: 4,
    gender: "men",
    productType: "bag",
    productImg: "http://localhost:5000/man-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 15,
    stock: 4,
    gender: "men",
    productType: "shoe",
    productImg: "http://localhost:5000/man-2.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 16,
    stock: 4,
    gender: "men",
    productType: "jacket",
    productImg: "http://localhost:5000/man-3.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 17,
    stock: 4,
    gender: "men",
    productType: "bag",
    productImg: "http://localhost:5000/man-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 18,
    stock: 10,
    gender: "men",
    productType: "bag",
    productImg: "http://localhost:5000/man-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 19,
    stock: 4,
    gender: "men",
    productType: "shoe",
    productImg: "http://localhost:5000/man-2.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 20,
    stock: 4,
    gender: "men",
    productType: "jacket",
    productImg: "http://localhost:5000/man-3.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 21,
    stock: 4,
    gender: "men",
    productType: "bag",
    productImg: "http://localhost:5000/man-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$54.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 22,
    stock: 4,
    gender: "men",
    productType: "bag",
    productImg: "http://localhost:5000/man-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 23,
    stock: 4,
    gender: "men",
    productType: "bag",
    productImg: "http://localhost:5000/man-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$24.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 24,
    stock: 4,
    gender: "men",
    productType: "bag",
    productImg: "http://localhost:5000/man-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 25,
    stock: "out of stock",
    gender: "men",
    productType: "bag",
    productImg: "http://localhost:5000/man-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$13.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 26,
    stock: 4,
    gender: "men",
    productType: "bag",
    productImg: "http://localhost:5000/man-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$14.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
  {
    id: 27,
    stock: 4,
    gender: "men",
    productType: "bag",
    productImg: "http://localhost:5000/man-1.jpg",
    productName: "Pure Pineapple",
    productPrice: "$12.00",
    productAbout:
      "Mill Oil is an innovative oil filled radiator with the most modern technology. If you are looking for something that can make your interior look awesome, and at the same time.",
  },
];
